<?php
/**
 * User Autoresponder and Mail Forwarder - Core Engine
 *
 * @copyright 2026 The SquirrelMail Project Team
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * @package plugins
 * @subpackage autoresponder
 */

if (!function_exists('getHashedFile') && defined('SM_PATH')) {
    include_once(SM_PATH . 'functions/prefs.php');
}

/**
 * Get config file path for user
 */
function autoresponder_get_config_file()
{
    global $username, $data_dir;
    return getHashedFile($username, $data_dir, "$username.autoresponder.json");
}

/**
 * Get history file path for tracking sent auto-replies
 */
function autoresponder_get_history_file()
{
    global $username, $data_dir;
    return getHashedFile($username, $data_dir, "$username.autoresponder_history.json");
}

/**
 * Load user autoresponder and forwarding configuration
 */
function autoresponder_get_config()
{
    $file = autoresponder_get_config_file();
    $defaults = array(
        'vacation_enabled'    => 0,
        'vacation_start'      => date('Y-m-d'),
        'vacation_end'        => date('Y-m-d', strtotime('+7 days')),
        'vacation_subject'    => 'Out of Office: {subject}',
        'vacation_body'       => "Hello,\n\nThank you for reaching out. I am currently out of the office and have limited access to email.\nI will respond to your message as soon as possible after my return.\n\nBest regards,",
        'vacation_interval'   => 1, // days between replies to same sender
        'forward_enabled'     => 0,
        'forward_addresses'   => '',
        'forward_keep_copy'   => 1
    );

    if (file_exists($file)) {
        $json = @file_get_contents($file);
        if (!empty($json)) {
            $data = json_decode($json, true);
            if (is_array($data)) {
                return array_merge($defaults, $data);
            }
        }
    }
    return $defaults;
}

/**
 * Save configuration
 */
function autoresponder_save_config($config)
{
    $file = autoresponder_get_config_file();
    return @file_put_contents($file, json_encode($config, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));
}

/**
 * Check if vacation responder is currently active (enabled and in date range)
 */
function autoresponder_is_vacation_active($config = null)
{
    if ($config === null) {
        $config = autoresponder_get_config();
    }

    if (empty($config['vacation_enabled'])) {
        return false;
    }

    $today = date('Y-m-d');
    if (!empty($config['vacation_start']) && $today < $config['vacation_start']) {
        return false;
    }
    if (!empty($config['vacation_end']) && $today > $config['vacation_end']) {
        return false;
    }

    return true;
}

/**
 * Check if sender should receive an auto-reply
 */
function autoresponder_can_reply_to($sender, $intervalDays = 1)
{
    $sender = strtolower(trim($sender));
    if (empty($sender) || !filter_var($sender, FILTER_VALIDATE_EMAIL)) {
        return false;
    }

    // Do not reply to mailing lists, bounces, or no-reply addresses
    if (preg_match('/mailer-daemon|postmaster|no-reply|noreply|bounce|donotreply|list-|request@/i', $sender)) {
        return false;
    }

    $file = autoresponder_get_history_file();
    $history = array();
    if (file_exists($file)) {
        $history = json_decode(@file_get_contents($file), true) ?: array();
    }

    $now = time();
    $minIntervalSec = $intervalDays * 86400;

    if (isset($history[$sender])) {
        $lastSent = intval($history[$sender]);
        if (($now - $lastSent) < $minIntervalSec) {
            return false; // Replied too recently
        }
    }

    return true;
}

/**
 * Record that an auto-reply was sent to sender
 */
function autoresponder_record_reply($sender)
{
    $sender = strtolower(trim($sender));
    $file = autoresponder_get_history_file();
    $history = array();
    if (file_exists($file)) {
        $history = json_decode(@file_get_contents($file), true) ?: array();
    }
    $history[$sender] = time();

    // Prune history older than 30 days
    $threshold = time() - (30 * 86400);
    foreach ($history as $s => $t) {
        if ($t < $threshold) unset($history[$s]);
    }

    @file_put_contents($file, json_encode($history));
}

/**
 * Generate Sieve script representation
 */
function autoresponder_generate_sieve($config)
{
    $sieve = "# Sieve Vacation and Forwarding Script generated by SquirrelMail\n";
    $sieve .= "require [\"vacation\", \"copy\"];\n\n";

    if (!empty($config['forward_enabled']) && !empty($config['forward_addresses'])) {
        $addrs = explode(',', $config['forward_addresses']);
        foreach ($addrs as $addr) {
            $cleanAddr = trim($addr);
            if (!empty($cleanAddr)) {
                if (!empty($config['forward_keep_copy'])) {
                    $sieve .= "redirect :copy \"" . addslashes($cleanAddr) . "\";\n";
                } else {
                    $sieve .= "redirect \"" . addslashes($cleanAddr) . "\";\n";
                }
            }
        }
        $sieve .= "\n";
    }

    if (!empty($config['vacation_enabled'])) {
        $days = intval($config['vacation_interval'] ?? 1);
        $subject = str_replace('{subject}', '$subject', $config['vacation_subject']);
        $body = $config['vacation_body'];

        $sieve .= "vacation\n";
        $sieve .= "  :days $days\n";
        $sieve .= "  :subject \"" . addslashes($subject) . "\"\n";
        $sieve .= "  \"" . addslashes($body) . "\";\n";
    }

    return $sieve;
}
